#!/bin/bash

NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'


auto-generate-config() {
echo "PROJECT_LIST=\"$(ls -d */)\"" >> .workspace.conf
    echo -e "=== ${GREEN}Configuration file successfully created, if you just want to access specific projects please modify the PROJECT_LIST in your configuration file \".workspace.conf\".${NC}"
}

# verify project folder
if [ ! -e ./.workspace.conf ]; then
    echo -e "=== ${ORANGE}Current folder seems not to be a project folder. (Project configuration file \".workspace.conf\" not found)${NC} ==="
    source openbase-script-utils
    echo -e "=== Should a configuration file be created for this folder and the projects be auto detected? ==="
    awaitConfirmation && auto-generate-config && exit 0
    exit 1 
fi
# load project configuration
source .workspace.conf


SKIP_ON_ERROR=${SKIP_ON_ERROR:-1}
ORIGIN_DIR=`pwd`

START=$(date +%s.%N)
for project in ${PROJECT_LIST}; do
    echo -e "=== ${BLUE}$project${NC} === "
    cd $project
    $DRY_RUN eval "$@"
    lastResult=$?
    if [ $lastResult  != 0 ] 
    then
        echo -e "=== ${RED}error by executing [$@] in project $project${NC} ==="
        if [ $SKIP_ON_ERROR  == 1 ] 
        then
            cd ..
            exit 1
        fi
    fi  

    cd $ORIGIN_DIR
    echo ""
done
END=$(date +%s.%N)
PROCESSING_TIME=$(echo "$END - $START" | bc)
echo -e "=== ${GREEN}finished${NC} in ${PROCESSING_TIME} sec ==="


auto-generate-config() {
   echo create stuff 
}
