#!/bin/bash

source openbase-script-utils

CONFIG_FOLDER=${HOME}/.config/
DEFAULT_CONFIG=${CONFIG_FOLDER}/bco


printStatus() {
    SELECTED_CONFIG=$(readlink ${DEFAULT_CONFIG})
    SELECTED=${SELECTED_CONFIG/${CONFIG_FOLDER}/''}
    SELECTED=${SELECTED/bco-/''}
    echo -e "selected: ${GREEN}${SELECTED}${NC} [ ${WHITE}${SELECTED_CONFIG}${NC} ]"
}

if [ -z ${1+x} ] || [ $1 == 'help' ] || [ $1 == 'h' ] || [ $1 == '--help' ] || [ $1 == '-h' ]; then
    echo -e "usage: bco-setup [CONFIG_ID]"
    echo -e "            Links the referred config as default bco config."
    echo -e "       bco-setup status | st"
    echo -e "            Displays the currently selected bco config."
    echo -e "       bco-setup avail | list"
    echo -e "           Print available configurations."
    echo -e "       bco-setup --help"
    echo -e "            Prints this help screen."
    echo -e ""
    echo -e "  e.g: ${WHITE}bco-setup home${NC} : ${BLUE}~/.config/bco${NC} --> ${BLUE}~/.config/bco-home${NC}"
    exit 0
fi

if [ $1 == 'status' ] || [ $1 == 'st' ]; then
    printStatus;
    exit 0
fi

if [ $1 == 'avail' ] || [ $1 == 'list' ] ; then
    echo -e ${WHITE}available:${GREEN}
    basename -a $(ls ~/.config/ | grep -Eo 'bco-[a-zA-Z]+' | cut -c 5-)
    echo -e ${NC}
    exit 0
fi

CONFIG=~/.config/bco-$1

if [ ! -e ~/.config/bco-${1} ] ; then
    echo -e ${RED}bco config ${WHITE}${CONFIG}${RED} not found!${NC}
    exit 1
fi

if [ -L ~/.config/bco ] ; then
   rm ~/.config/bco
fi

ln -sf ~/.config/bco-${1} ${DEFAULT_CONFIG}
printStatus


