#!/bin/bash

# configure exit on error
set -e

upgrade(){
    clear
    echo "=== upgrade ==="
    echo "please make sure all local changes are commited and pushed to the remote repository and press any key to confirm..."
    read &&
    echo "=== sync ===" && 
    git pull &&
    echo "press any key to continue..."
    read &&
    mvn release:update-versions -DautoVersionSubmodules -Dresume=false &&
    git commit -am "upgrade devel version." &&
    git push &&

    echo "=== final sync ===" &&
    git pull &&
    echo finished
}

upgrade $@
