#!/bin/bash

# configure exit on error
set -e

mvn clean install -o -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Dsource.skip=true -DskipAddThirdParty=true -Dlicense.skipUpdateProjectLicense=true -Dmaven.license.skip=true

