#!/bin/bash

# ALWAYS LOAD DEFAULT COMMAND LINE ASCI COLORS

    NC='\033[0m'
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    ORANGE='\033[0;33m'
    BLUE='\033[0;34m'
    WHITE='\033[0;37m'

awaitConfirmation(){
    read -p "Please type ${GREEN}y${NC} to confirm: " -n 1 -r &&
    echo &&  # new line
    if [[ ! $REPLY =~ ^[YyZz]$ ]]; then
        echo "=== Action aborted by user..."
        return 255
    fi
}

