#!/bin/bash

upgrade(){

    echo "=== sync ===" && 
    git pull --rebase &&
    echo please confirm to continue...
    read &&
    mvn release:update-versions -DautoVersionSubmodules -Dresume=false &&
    git commit -am "upgrade devel version." &&
    git push &&

    echo "=== final sync ===" &&
    git pull &&
    echo finished
}

upgrade $@
