#!/bin/bash

# configure exit on error
set -e

upgrade(){

    echo "=== sync ===" && 
    git pull --rebase &&
    read &&
    mvn release:update-versions -DautoVersionSubmodules -Dresume=false &&
    git commit -am "upgrade devel version." &&
    git push &&

    echo "=== final sync ===" &&
    git pull &&
    echo finished
}

upgrade $@
